packages:
  # https://github.com/iTwin/itwinjs-core
  - '../imodeljs/core/*'
  - '../imodeljs/presentation/*'
  - '../imodeljs/tools/*'
  - '../imodeljs/ui/*'
  # https://github.com/iTwin/viewer
  - '../viewer/packages/apps/web-viewer-test/*'
  - '../viewer/packages/apps/desktop-viewer-test/*'
  - '../viewer/packages/modules/*'
  # https://github.com/iTwin/viewer-components-react
  - '../viewer-components-react/packages/itwin/*'
  # https://github.com/iTwin/auth-clients
  - '../auth-clients/packages/*'